blank_issues_enabled: false
contact_links:
  - name: 💼 Trabaja con Nosotros 💼
    url: https://api.whatsapp.com/send/?phone=593969494350&text=%C2%A1Hola%21+Me+interesa+trabajar+con+ustedes.
    about: Para oportunidades laborales o colaboración, contáctanos por WhatsApp.
